# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UnityGeneral.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='UnityGeneral.proto',
  package='unitycomm',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12UnityGeneral.proto\x12\tunitycomm\"E\n\x07Request\x12\x0c\n\x04\x66unc\x18\x01 \x01(\t\x12\x0c\n\x04info\x18\x02 \x01(\t\x12\x1e\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x10.unitycomm.UData\"I\n\x08Response\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0c\n\x04info\x18\x02 \x01(\t\x12\x1e\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x10.unitycomm.UData\"\x95\x01\n\x05UData\x12\x17\n\nbytes_data\x18\x01 \x01(\x0cH\x00\x88\x01\x01\x12-\n\nvar_single\x18\x02 \x01(\x0b\x32\x14.unitycomm.MultiTypeH\x01\x88\x01\x01\x12&\n\x08var_list\x18\x03 \x03(\x0b\x32\x14.unitycomm.MultiTypeB\r\n\x0b_bytes_dataB\r\n\x0b_var_single\"\x86\x01\n\tMultiType\x12\x13\n\tint_value\x18\x01 \x01(\x05H\x00\x12\x14\n\nlong_value\x18\x02 \x01(\x03H\x00\x12\x15\n\x0b\x66loat_value\x18\x03 \x01(\x02H\x00\x12\x16\n\x0c\x64ouble_value\x18\x04 \x01(\x01H\x00\x12\x16\n\x0cstring_value\x18\x05 \x01(\tH\x00\x42\x07\n\x05value2I\n\x10UnityGrpcService\x12\x35\n\nRemoteCall\x12\x12.unitycomm.Request\x1a\x13.unitycomm.Responseb\x06proto3'
)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='unitycomm.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='func', full_name='unitycomm.Request.func', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='info', full_name='unitycomm.Request.info', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='unitycomm.Request.data', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=102,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='unitycomm.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='unitycomm.Response.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='info', full_name='unitycomm.Response.info', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='unitycomm.Response.data', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=177,
)


_UDATA = _descriptor.Descriptor(
  name='UData',
  full_name='unitycomm.UData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bytes_data', full_name='unitycomm.UData.bytes_data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='var_single', full_name='unitycomm.UData.var_single', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='var_list', full_name='unitycomm.UData.var_list', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_bytes_data', full_name='unitycomm.UData._bytes_data',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_var_single', full_name='unitycomm.UData._var_single',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=180,
  serialized_end=329,
)


_MULTITYPE = _descriptor.Descriptor(
  name='MultiType',
  full_name='unitycomm.MultiType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='int_value', full_name='unitycomm.MultiType.int_value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='long_value', full_name='unitycomm.MultiType.long_value', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='float_value', full_name='unitycomm.MultiType.float_value', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='double_value', full_name='unitycomm.MultiType.double_value', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='string_value', full_name='unitycomm.MultiType.string_value', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value', full_name='unitycomm.MultiType.value',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=332,
  serialized_end=466,
)

_REQUEST.fields_by_name['data'].message_type = _UDATA
_RESPONSE.fields_by_name['data'].message_type = _UDATA
_UDATA.fields_by_name['var_single'].message_type = _MULTITYPE
_UDATA.fields_by_name['var_list'].message_type = _MULTITYPE
_UDATA.oneofs_by_name['_bytes_data'].fields.append(
  _UDATA.fields_by_name['bytes_data'])
_UDATA.fields_by_name['bytes_data'].containing_oneof = _UDATA.oneofs_by_name['_bytes_data']
_UDATA.oneofs_by_name['_var_single'].fields.append(
  _UDATA.fields_by_name['var_single'])
_UDATA.fields_by_name['var_single'].containing_oneof = _UDATA.oneofs_by_name['_var_single']
_MULTITYPE.oneofs_by_name['value'].fields.append(
  _MULTITYPE.fields_by_name['int_value'])
_MULTITYPE.fields_by_name['int_value'].containing_oneof = _MULTITYPE.oneofs_by_name['value']
_MULTITYPE.oneofs_by_name['value'].fields.append(
  _MULTITYPE.fields_by_name['long_value'])
_MULTITYPE.fields_by_name['long_value'].containing_oneof = _MULTITYPE.oneofs_by_name['value']
_MULTITYPE.oneofs_by_name['value'].fields.append(
  _MULTITYPE.fields_by_name['float_value'])
_MULTITYPE.fields_by_name['float_value'].containing_oneof = _MULTITYPE.oneofs_by_name['value']
_MULTITYPE.oneofs_by_name['value'].fields.append(
  _MULTITYPE.fields_by_name['double_value'])
_MULTITYPE.fields_by_name['double_value'].containing_oneof = _MULTITYPE.oneofs_by_name['value']
_MULTITYPE.oneofs_by_name['value'].fields.append(
  _MULTITYPE.fields_by_name['string_value'])
_MULTITYPE.fields_by_name['string_value'].containing_oneof = _MULTITYPE.oneofs_by_name['value']
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['UData'] = _UDATA
DESCRIPTOR.message_types_by_name['MultiType'] = _MULTITYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'UnityGeneral_pb2'
  # @@protoc_insertion_point(class_scope:unitycomm.Request)
  })
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'UnityGeneral_pb2'
  # @@protoc_insertion_point(class_scope:unitycomm.Response)
  })
_sym_db.RegisterMessage(Response)

UData = _reflection.GeneratedProtocolMessageType('UData', (_message.Message,), {
  'DESCRIPTOR' : _UDATA,
  '__module__' : 'UnityGeneral_pb2'
  # @@protoc_insertion_point(class_scope:unitycomm.UData)
  })
_sym_db.RegisterMessage(UData)

MultiType = _reflection.GeneratedProtocolMessageType('MultiType', (_message.Message,), {
  'DESCRIPTOR' : _MULTITYPE,
  '__module__' : 'UnityGeneral_pb2'
  # @@protoc_insertion_point(class_scope:unitycomm.MultiType)
  })
_sym_db.RegisterMessage(MultiType)



_UNITYGRPCSERVICE = _descriptor.ServiceDescriptor(
  name='UnityGrpcService',
  full_name='unitycomm.UnityGrpcService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=468,
  serialized_end=541,
  methods=[
  _descriptor.MethodDescriptor(
    name='RemoteCall',
    full_name='unitycomm.UnityGrpcService.RemoteCall',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_UNITYGRPCSERVICE)

DESCRIPTOR.services_by_name['UnityGrpcService'] = _UNITYGRPCSERVICE

# @@protoc_insertion_point(module_scope)
