# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import UnityGeneral_pb2 as UnityGeneral__pb2


class UnityGrpcServiceStub(object):
    """服务定义
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RemoteCall = channel.unary_unary(
                '/unitycomm.UnityGrpcService/RemoteCall',
                request_serializer=UnityGeneral__pb2.Request.SerializeToString,
                response_deserializer=UnityGeneral__pb2.Response.FromString,
                )


class UnityGrpcServiceServicer(object):
    """服务定义
    """

    def RemoteCall(self, request, context):
        """定义一个RPC调用，用于发送请求并接收响应
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UnityGrpcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RemoteCall': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoteCall,
                    request_deserializer=UnityGeneral__pb2.Request.FromString,
                    response_serializer=UnityGeneral__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'unitycomm.UnityGrpcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UnityGrpcService(object):
    """服务定义
    """

    @staticmethod
    def RemoteCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/unitycomm.UnityGrpcService/RemoteCall',
            UnityGeneral__pb2.Request.SerializeToString,
            UnityGeneral__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
