# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import face_recognition_pb2 as face__recognition__pb2


class FaceDetectServiceStub(object):
    """定义服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectFaces = channel.unary_unary(
                '/facerecognition.FaceDetectService/DetectFaces',
                request_serializer=face__recognition__pb2.FaceDetectRequest.SerializeToString,
                response_deserializer=face__recognition__pb2.FaceDetectResponse.FromString,
                )


class FaceDetectServiceServicer(object):
    """定义服务
    """

    def DetectFaces(self, request, context):
        """定义一个RPC调用，客户端发送请求，服务器返回响应
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FaceDetectServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectFaces': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectFaces,
                    request_deserializer=face__recognition__pb2.FaceDetectRequest.FromString,
                    response_serializer=face__recognition__pb2.FaceDetectResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'facerecognition.FaceDetectService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FaceDetectService(object):
    """定义服务
    """

    @staticmethod
    def DetectFaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/facerecognition.FaceDetectService/DetectFaces',
            face__recognition__pb2.FaceDetectRequest.SerializeToString,
            face__recognition__pb2.FaceDetectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
