# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: face_recognition.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='face_recognition.proto',
  package='facerecognition',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16\x66\x61\x63\x65_recognition.proto\x12\x0f\x66\x61\x63\x65recognition\"n\n\x04\x46\x61\x63\x65\x12,\n\x06gender\x18\x01 \x01(\x0e\x32\x1c.facerecognition.Face.Gender\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x12\x0b\n\x03\x62ox\x18\x03 \x03(\x05\"\x1e\n\x06Gender\x12\n\n\x06\x46\x45MALE\x10\x00\x12\x08\n\x04MALE\x10\x01\")\n\x11\x46\x61\x63\x65\x44\x65tectRequest\x12\x14\n\x0cimage_base64\x18\x01 \x01(\t\"=\n\x12\x46\x61\x63\x65\x44\x65tectResponse\x12\'\n\x08subjects\x18\x01 \x03(\x0b\x32\x15.facerecognition.Face2k\n\x11\x46\x61\x63\x65\x44\x65tectService\x12V\n\x0b\x44\x65tectFaces\x12\".facerecognition.FaceDetectRequest\x1a#.facerecognition.FaceDetectResponseb\x06proto3'
)



_FACE_GENDER = _descriptor.EnumDescriptor(
  name='Gender',
  full_name='facerecognition.Face.Gender',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FEMALE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MALE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=123,
  serialized_end=153,
)
_sym_db.RegisterEnumDescriptor(_FACE_GENDER)


_FACE = _descriptor.Descriptor(
  name='Face',
  full_name='facerecognition.Face',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='gender', full_name='facerecognition.Face.gender', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='age', full_name='facerecognition.Face.age', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='box', full_name='facerecognition.Face.box', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _FACE_GENDER,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=153,
)


_FACEDETECTREQUEST = _descriptor.Descriptor(
  name='FaceDetectRequest',
  full_name='facerecognition.FaceDetectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='image_base64', full_name='facerecognition.FaceDetectRequest.image_base64', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=196,
)


_FACEDETECTRESPONSE = _descriptor.Descriptor(
  name='FaceDetectResponse',
  full_name='facerecognition.FaceDetectResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='subjects', full_name='facerecognition.FaceDetectResponse.subjects', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=259,
)

_FACE.fields_by_name['gender'].enum_type = _FACE_GENDER
_FACE_GENDER.containing_type = _FACE
_FACEDETECTRESPONSE.fields_by_name['subjects'].message_type = _FACE
DESCRIPTOR.message_types_by_name['Face'] = _FACE
DESCRIPTOR.message_types_by_name['FaceDetectRequest'] = _FACEDETECTREQUEST
DESCRIPTOR.message_types_by_name['FaceDetectResponse'] = _FACEDETECTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Face = _reflection.GeneratedProtocolMessageType('Face', (_message.Message,), {
  'DESCRIPTOR' : _FACE,
  '__module__' : 'face_recognition_pb2'
  # @@protoc_insertion_point(class_scope:facerecognition.Face)
  })
_sym_db.RegisterMessage(Face)

FaceDetectRequest = _reflection.GeneratedProtocolMessageType('FaceDetectRequest', (_message.Message,), {
  'DESCRIPTOR' : _FACEDETECTREQUEST,
  '__module__' : 'face_recognition_pb2'
  # @@protoc_insertion_point(class_scope:facerecognition.FaceDetectRequest)
  })
_sym_db.RegisterMessage(FaceDetectRequest)

FaceDetectResponse = _reflection.GeneratedProtocolMessageType('FaceDetectResponse', (_message.Message,), {
  'DESCRIPTOR' : _FACEDETECTRESPONSE,
  '__module__' : 'face_recognition_pb2'
  # @@protoc_insertion_point(class_scope:facerecognition.FaceDetectResponse)
  })
_sym_db.RegisterMessage(FaceDetectResponse)



_FACEDETECTSERVICE = _descriptor.ServiceDescriptor(
  name='FaceDetectService',
  full_name='facerecognition.FaceDetectService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=261,
  serialized_end=368,
  methods=[
  _descriptor.MethodDescriptor(
    name='DetectFaces',
    full_name='facerecognition.FaceDetectService.DetectFaces',
    index=0,
    containing_service=None,
    input_type=_FACEDETECTREQUEST,
    output_type=_FACEDETECTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FACEDETECTSERVICE)

DESCRIPTOR.services_by_name['FaceDetectService'] = _FACEDETECTSERVICE

# @@protoc_insertion_point(module_scope)
