# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import portrait_stylization_pb2 as portrait__stylization__pb2


class PortraitStylizationStub(object):
    """The image processing service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StylizeImage = channel.unary_unary(
                '/portraitstylization.PortraitStylization/StylizeImage',
                request_serializer=portrait__stylization__pb2.ImageRequest.SerializeToString,
                response_deserializer=portrait__stylization__pb2.ImageReply.FromString,
                )


class PortraitStylizationServicer(object):
    """The image processing service definition.
    """

    def StylizeImage(self, request, context):
        """Sends an image and receives a stylized version of it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PortraitStylizationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StylizeImage': grpc.unary_unary_rpc_method_handler(
                    servicer.StylizeImage,
                    request_deserializer=portrait__stylization__pb2.ImageRequest.FromString,
                    response_serializer=portrait__stylization__pb2.ImageReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'portraitstylization.PortraitStylization', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PortraitStylization(object):
    """The image processing service definition.
    """

    @staticmethod
    def StylizeImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/portraitstylization.PortraitStylization/StylizeImage',
            portrait__stylization__pb2.ImageRequest.SerializeToString,
            portrait__stylization__pb2.ImageReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
