# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: portrait_stylization.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aportrait_stylization.proto\x12\x13portraitstylization\"R\n\x0cImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0f\n\x07\x63hannel\x18\x04 \x01(\x05\" \n\nImageReply\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x32k\n\x13PortraitStylization\x12T\n\x0cStylizeImage\x12!.portraitstylization.ImageRequest\x1a\x1f.portraitstylization.ImageReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'portrait_stylization_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IMAGEREQUEST']._serialized_start=51
  _globals['_IMAGEREQUEST']._serialized_end=133
  _globals['_IMAGEREPLY']._serialized_start=135
  _globals['_IMAGEREPLY']._serialized_end=167
  _globals['_PORTRAITSTYLIZATION']._serialized_start=169
  _globals['_PORTRAITSTYLIZATION']._serialized_end=276
# @@protoc_insertion_point(module_scope)
